# Generated by Django 4.0.2 on 2022-02-10 19:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=1)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('contract', models.CharField(choices=[('tenant', 'Tenant'), ('sublet', 'Sublet'), ('legal', 'Legal'), ('unspecified', 'Unspecified')], default='unspecified', max_length=12)),
                ('rent', models.FloatField(default=0.0)),
                ('start_date', models.DateField(default=datetime.datetime(2022, 2, 10, 19, 25, 24, 436014))),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=300)),
                ('amount', models.FloatField(default=0.0)),
                ('type', models.CharField(choices=[('INC', 'income'), ('EXP', 'expense')], max_length=3)),
                ('VAT_rate', models.CharField(choices=[('NOR', 'normal(20%)'), ('MID', 'middle(10%)'), ('RED', 'reduced(5,5%)'), ('SPE', 'special(2,1%)'), ('NUL', 'null'), ('ND', 'undetermined')], default='ND', max_length=3)),
                ('date', models.DateField(default=datetime.datetime(2022, 2, 10, 19, 25, 24, 512114))),
            ],
        ),
        migrations.CreateModel(
            name='Distribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0.0)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.entry')),
            ],
        ),
    ]
