# Generated by Django 4.0 on 2022-02-25 18:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0002_alter_account_start_date_alter_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 19, 31, 18, 705557)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 2, 25, 19, 31, 18, 743738)),
        ),
    ]
