# Generated by Django 4.0 on 2022-03-03 21:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0003_alter_account_start_date_alter_entry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='unique_id',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 3, 3, 22, 43, 47, 417279)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 3, 3, 22, 43, 47, 461757)),
        ),
    ]
