# Generated by Django 4.0 on 2022-04-01 10:15

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0004_entry_unique_id_alter_account_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 12, 15, 2, 284850)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 12, 15, 2, 325893)),
        ),
        migrations.CreateModel(
            name='PrintsDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0)),
                ('type', models.CharField(choices=[('B&W', 'black_and_white'), ('C', 'color')], max_length=3)),
                ('date', models.DateField(default=datetime.datetime(2022, 4, 1, 12, 15, 2, 326665))),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.account')),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='comptabilite.entry')),
            ],
        ),
    ]
