# Generated by Django 4.0 on 2022-04-01 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0006_alter_account_start_date_alter_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 13, 34, 17, 371744)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 13, 34, 17, 409495)),
        ),
        migrations.AlterField(
            model_name='printsdistribution',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 1, 13, 34, 17, 410315)),
        ),
    ]
