# Generated by Django 4.0.4 on 2022-08-01 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptabilite', '0007_alter_account_start_date_alter_entry_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 8, 1, 19, 24, 2, 174690)),
        ),
        migrations.AlterField(
            model_name='entry',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 1, 19, 24, 2, 247236)),
        ),
        migrations.AlterField(
            model_name='printsdistribution',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 8, 1, 19, 24, 2, 248231)),
        ),
    ]
